general:
  debug: false
  instance_name: "searxng"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: true
  open_metrics: ""

brand:
  new_issue_url: https://github.com/searxng/searxng/issues/new
  docs_url: https://docs.searxng.org/
  public_instances: https://searx.space
  wiki_url: https://github.com/searxng/searxng/wiki
  issue_url: https://github.com/searxng/searxng/issues

search:
  safe_search: 0
  autocomplete: ""
  autocomplete_min: 4
  favicon_resolver: ""
  default_lang: "auto"
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120
  suspended_times:
    # Engine suspension time after error (in seconds; set to 0 to disable)
    # For error "Access denied" and "HTTP error [402, 403]"
    SearxEngineAccessDenied: 86400
    # For error "CAPTCHA"
    SearxEngineCaptcha: 86400
    # For error "Too many request" and "HTTP error 429"
    SearxEngineTooManyRequests: 3600
    # Cloudflare CAPTCHA
    cf_SearxEngineCaptcha: 1296000
    cf_SearxEngineAccessDenied: 86400
    # ReCAPTCHA
    recaptcha_SearxEngineCaptcha: 604800

  formats:
    - html
    - json

server:
  bind_address: "0.0.0.0"
  base_url: /
  limiter: false
  public_instance: false

  secret_key: "a48ea95e8eb0b9997e8285bcfeea0bc34802ade2f5fdb0d336b1d82a3959eed7" # Is overwritten by ${SEARXNG_SECRET}
  image_proxy: false
  http_protocol_version: "1.0"
  method: "POST"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

valkey:
  url: VALKEY_URL_PLACEHOLDER

ui:
  static_path: ""
  static_use_hash: false
  templates_path: ""
  query_in_title: false
  infinite_scroll: false
  default_theme: simple
  center_alignment: false
  default_locale: ""
  theme_args:
    simple_style: auto
  search_on_category_select: true
  hotkeys: default
  url_formatting: pretty

outgoing:
  request_timeout: 3.0
  useragent_suffix: ""
  pool_connections: 100
  pool_maxsize: 20
  enable_http2: true

checker:
  off_when_debug: true
  additional_tests:
    rosebud: &test_rosebud
      matrix:
        query: rosebud
        lang: en
      result_container:
        - not_empty
        - ["one_title_contains", "citizen kane"]
      test:
        - unique_results

    android: &test_android
      matrix:
        query: ["android"]
        lang: ["en", "de", "fr", "zh-CN"]
      result_container:
        - not_empty
        - ["one_title_contains", "google"]
      test:
        - unique_results

  # tests: only for the YAML anchors (see the engines section)
  tests:
    infobox: &tests_infobox
      infobox:
        matrix:
          query: ["linux", "new york", "bbc"]
        result_container:
          - has_infobox

categories_as_tabs:
  general:
  images:
  videos:
  news:
  map:
  music:
  it:
  science:
  files:
  social media:

engines:
  # DuckDuckGo (https://duckduckgo.com/)
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    categories: [general, web]
    disabled: false

  # GitHub (https://github.com/)
  - name: github
    engine: github
    shortcut: gh
    categories: [it, repos]
    disabled: false

  # Google (https://www.google.com/)
  - name: google
    engine: google
    shortcut: go
    categories: [general, web]
    disabled: false

doi_resolvers:
  oadoi.org: "https://oadoi.org/"
  doi.org: "https://doi.org/"
  doai.io: "https://dissem.in/"

default_doi_resolver: "oadoi.org"
