#!/usr/bin/env bash

set -e

### LAB

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
    CREATE USER "${LAB_POSTGRES_USER}" WITH PASSWORD '${LAB_POSTGRES_PASSWORD}';
    CREATE DATABASE "${LAB_POSTGRES_DATABASE}" OWNER "${LAB_POSTGRES_USER}";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$LAB_POSTGRES_USER" --dbname "${LAB_POSTGRES_DATABASE}" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS vector;
EOSQL
